limits:
  max-money-per-minute: 1000000.0
  suspicious-transaction: 50000000.0

monitoring:
  check-interval-seconds: 10
  players-per-scan: 3

actions:
  auto-remove-money: true

logging:
  log-to-file: true