name: MoneyGuard
version: '1.0'
main: com.Lino.moneyGuard.MoneyGuard
api-version: '1.21'
author: Lino
description: Advanced economy monitoring and protection plugin
depend: [Vault]

commands:
  moneyguard:
    description: Main MoneyGuard command
    usage: /<command> [reload|check|warn|reset|help]
    permission: moneyguard.use
    aliases: [mg]
  mg:
    description: MoneyGuard alias
    usage: /<command> [reload|check|warn|reset|help]
    permission: moneyguard.use

permissions:
  moneyguard.use:
    description: Allows use of MoneyGuard commands
    default: op
  moneyguard.admin:
    description: Full access to all MoneyGuard features
    default: op
    children:
      moneyguard.use: true
      moneyguard.reload: true
      moneyguard.check: true
      moneyguard.warn: true
      moneyguard.reset: true
      moneyguard.alerts: true
      moneyguard.gui: true
  moneyguard.reload:
    description: Reload the plugin configuration
    default: op
  moneyguard.check:
    description: Check player money statistics
    default: op
  moneyguard.warn:
    description: Warn players for violations
    default: op
  moneyguard.reset:
    description: Reset player warnings
    default: op
  moneyguard.alerts:
    description: Receive economy alerts
    default: op
  moneyguard.gui:
    description: Access the GUI interface
    default: op
  moneyguard.bypass:
    description: Bypass all economy checks
    default: false